spring.application.name=VK_monetisation

spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PSQL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.docker.compose.enabled=false

server.port=8080

app.tx.campaign-activation-duration-minutes=4
app.tx.simulate-ledger-failure=false
app.tx.ledger.jndi-name=java:/jdbc/VkMonetisationLedgerXA
