spring.datasource.jndi-name=java:/jdbc/VkMonetisationMainXA

spring.jpa.properties.hibernate.transaction.coordinator_class=jta
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.WildFlyStandAloneJtaPlatform

app.tx.ledger.jndi-name=java:/jdbc/VkMonetisationLedgerXA

spring.jpa.hibernate.ddl-auto=update

